mod 'boxen', '2.1.0', :github_tarball => 'boxen/puppet-boxen'
mod 'stdlib', '4.1.0', :github_tarball => "puppetlabs/puppetlabs-stdlib"
mod 'sublime_text_2', '1.2.0', :github_tarball => "jozefizso/puppet-sublime_text_2"
