#!/bin/sh
# Make sure deps are available and run a Cardboard command.

set -e

cd $(dirname "$0")/..

MODULE_PATH=spec/fixtures/modules
PUPPET_ARGS="--modulepath=$MODULE_PATH --verbose"
SITE_FILE=spec/fixtures/manifests/site.pp
# [ "cibuild" = "$SCRIPT" ] && BUNDLE_ARGS="$BUNDLE_ARGS --no-quiet"

bundle exec cardboard bootstrap
bundle exec puppet apply $PUPPET_ARGS $SITE_FILE
